name: Build macOS App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Debug - List files
      run: |
        echo "=== Files in root ==="
        ls -la
        echo "=== Package.json content ==="
        cat package.json
        
    - name: Build macOS app
      run: |
        echo "Building macOS app..."
        npx electron-builder --mac dmg
      env:
        CSC_IDENTITY_AUTO_DISCOVERY: false
        
    - name: List build output
      run: |
        echo "=== Dist folder contents ==="
        ls -la dist/ || echo "No dist folder"
        
    - name: Upload macOS build
      uses: actions/upload-artifact@v3
      with:
        name: macos-app
        path: dist/
        if-no-files-found: warn
