name: Build macOS App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci --only=production || npm install
      
    - name: Build for macOS
      run: npx electron-builder --mac --publish=never
      env:
        CSC_IDENTITY_AUTO_DISCOVERY: false
        
    - name: Upload macOS DMG
      uses: actions/upload-artifact@v3
      with:
        name: Folder-Manager-macOS
        path: dist/*.dmg
        retention-days: 30
