name: Simple Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    - run: npm install
    - run: npm install -g electron-builder
    - run: npx electron-builder --win
    - uses: actions/upload-artifact@v4
      with:
        name: windows-app
        path: dist/*.exe

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    - run: npm install
    - run: npm install -g electron-builder
    - run: npx electron-builder --mac
      env:
        CSC_IDENTITY_AUTO_DISCOVERY: false
    - uses: actions/upload-artifact@v4
      with:
        name: macos-app
        path: dist/*.dmg

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    - run: npm install
    - run: npm install -g electron-builder
    - run: npx electron-builder --linux
    - uses: actions/upload-artifact@v4
      with:
        name: linux-app
        path: dist/*.AppImage
